In [2]:
print("hello Nav")

"Hello Nav"

hello Nav


'Hello Nav'

In [3]:
val = input("Enter val:")

In [4]:
print(val)

6


In [5]:
vala = input("Enter vala:")
valb = input("Enter valb:")


##Arithmatic 

In [6]:
val1 = 1023
val2 = 7

add = val1 + val2
print(f"The sum is {add}.")

The sum is 1030.


In [7]:
sub = val1 - val2
print(f"The difference is {sub}.")
mul = val1 * val2
print(f"The product is {mul}.")
div = val1/val2
print(f"The product is {div}.")
quo = val1//val2
print(f"The product is {quo}.")


The difference is 1016.
The product is 7161.
The product is 146.14285714285714.
The product is 146.


Great way to hide the last few digits of something use the // fundtion and divide it by how many decimals you see

In [8]:
print(1234567890//1000)

1234567


In [9]:
rem = val1%val2
print(f"The remainder is {rem}.")

The remainder is 1.


In [10]:
print(1234567890%1000)

890


In [11]:
pow = val1**val2 #val1^val2
print(f"Val1 to the Power of Val2 is {pow}.")

Val1 to the Power of Val2 is 1172544775637859048447.


Scientific Notation 

scientific = format(pow, ".2e")
.2e is # of decimals after point
e is 10 in this case

In [12]:
scientific = format(pow, ".2e")
print(scientific)

1.17e+21


Now I want to round the division decimal 

In [13]:
dec2a = round(div,2)
print(dec2a)
dec2b = round(div, ndigits=2)
print(dec2b)

146.14
146.14


Typecasting - converting from one data type to another

In [14]:
string1 = "123"
vals1 = int(string1)
print(type(string1))
print(type(vals1))

<class 'str'>
<class 'int'>


Input 3 values multiply the first two and divide that answer by the 3rd 

In [15]:
vala = input("Enter vala:")
valb = input("Enter valb:")
valc = input("Enter valc:")

In [16]:
vala = int(vala)
valb = int(valb)
valc = int(valc)

In [17]:
valprod = vala * valb
valdiv = valprod/valc
print(valdiv)

5.6


(((val * 2)+5)*92) find quotient and reminder
then /11 find quotient and reminder
val - 102 but input it

In [20]:
valNew = int(input("Enter valNew:"))
valNew = valNew * 2
valNew = valNew + 5
valNew = valNew * 92
print(valNew//11)
print(valNew%11)

1748
0


Anyting turned into a boolean value that is not 0 is true

In [23]:
valbol = "test"
print (valbol)
valbol = bool(valbol)
print(valbol)

test
True


String Manipulation 

Strings are stored like a list of characters in the memory with their own indexes (0 to n for each letter)

In [24]:
s1 = "NavIsAwesome"
print(s1*2)

NavIsAwesomeNavIsAwesome


In [25]:
s2 = "Ofcourse"
print (s1+s2)

NavIsAwesomeOfcourse


In [26]:
print ("A" in s1)

True


Is the letter A (case sensitive) in s1

In [27]:
print ("A" in s2)

False


3rd value in s1

In [28]:
print(s1[2])

v


First 3 values in s1. The last value is the value you stop before. So 3 gives 2 but not 3rd value (again starting from 0).

In [33]:
print(s1[0:3])
print(s1[:3])

Nav
Nav


Just the substring Awesome 

In [32]:
print(s1[5:12])
print(s1[5:])

Awesome
Awesome


Just Is

In [34]:
print(s1[3:5])

Is


In [39]:
#size of string
print(len(s1))
#The last index is length minus 1 (12 - 1 = 11). 
# Again because python starts at 0
#Last 4 digits
print(s1[len(s1)-4:])

12
some


In [44]:
#make something uppercase (you dont put anything in parenthesis)
print(s2.upper())
#make something lowercase (you dont put anything in parenthesis)
print(s2.lower())

print(s2[0].upper()+s2[1:].lower())

OFCOURSE
ofcourse
Ofcourse


In [46]:
#replace function
#Replace e with a $
print(s1.replace('e','$'))

NavIsAw$som$


Lists

lists can have multiple types of values

1st value -> index 0
2nd balue -> index 1

In [81]:
my_list = [1,2,"hi",True,4.1] #1-d List
my_list1 = [[0, 9, "fuck"], [True, 2.5]] #list of lists 

print(my_list[2:4])
#print the first index in the first list
print(my_list[1])
#print the 1st list in my_list1
print(my_list1[0])
#print the 2nd value in gthe first list of my_list1
print(my_list1[0][1])


['hi', True]
2
[0, 9, 'fuck']
9


List Functions

In [82]:
# Index location in the list where 4.1 is
print(my_list.index(4.1))
#What data type is in index 0 on the list. Checking the balue of the first comment in the list
print(type(my_list[0]))

# .append changes the original list and you dont need to set it equal to itself
my_list.append('!')
print(my_list)


4
<class 'int'>
[1, 2, 'hi', True, 4.1, '!']


In [83]:
#reverses the order of the list
my_list.reverse()
print(my_list)
#list operations makes changes in the original list

['!', 4.1, True, 'hi', 2, 1]


In [84]:
#finds 3rd from the back
print(my_list[-3])

#pop removes the value from the end of this list (changes the original list)
# and gives you that value
print(my_list.pop())
print(my_list)

hi
1
['!', 4.1, True, 'hi', 2]


In [ ]:
#pop removes the index that you give it unless you give it 
# nothing than it gives you the last value
print(my_list.pop(0))

!


In [120]:
a = 6
b = 5

If-Else
if <condition>:
elif <condition2>:
else: 

and = all true otherwise false
or = all false otherwise true

In [121]:
print(a%2 == 0)
print(a%2 == 0 and a < 5 and a > 4)
print(a%2 == 0 or  a < 5 or a > 4)
print(not (a%2 == 0 or  a < 5 or a > 4))

True
False
True
False


In [127]:
if a%2 == 0:
    EvOd = "even"
else: 
    EvOd = "odd"
print(f"{a} is an {EvOd} number.")

6 is an even number.


In [123]:
if a > 1 and a < 10:
    print("in range")
elif a<1:
    print("before range")
else:
    print ("outside range")

in range


The issue with this version is that you check multiple conditions. Unlike elif where if you pass the first codition 

In [124]:
if a > 1 and a < 10:
    print("in range")
if a<1:
    print("before range")

in range


Loop Statements

While - When you dont know the number of steps/repetitions you have to take 

For - When you know the number of steps/repetitions you have to take

In [ ]:
#while loop
password = "1234"
inp = ""
while password != inp: #loops till the condition is false
    inp= input ("Enter Password:")
print ("You're in!")

You're in!


In [ ]:
#for loop
#print first 5 whole numbers
for i in range (5):
    print (i)

0
1
2
3
4


In [130]:
#print first 5 natural numbers
for i in range (1,6):
    print (i)

1
2
3
4
5


Lopps and Lists
my_list=[1,2,'hi',True,4.1]

In [ ]:
#this command applies to the whole string

my_list=[1,2,'hi',True,4.1]
#convert all to string
my_list = str(my_list)
print(type(my_list[0]))

<class 'str'>


In [136]:
#this command changes all using a loop

my_list=[1,2,'hi',True,4.1]
#convert all to string
print("old list")
new_list = []
for element in my_list:
    print (type (element))
    new_list.append(str(element))
print("new list")
#check
for element in new_list:
    print(type(element))

old list
<class 'int'>
<class 'int'>
<class 'str'>
<class 'bool'>
<class 'float'>
new list
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Break = get out of the loop often used with if condition to break if condition is met

In [137]:
age = 25
name = 'Nav'
for i in range (age):
    if i ==10:
        break
    print(name) 


Nav
Nav
Nav
Nav
Nav
Nav
Nav
Nav
Nav
Nav


In [140]:
countn = 0
while True:
    countn = countn +1
    print(countn)
    if countn ==5:
        break

1
2
3
4
5


Functions

def define a function as 

def my_func(a,b): 
a and b are parameters
-func body-

def my_func(a:int, b:int) -> boll
a and b are supposed to be integers and it will return a boolean value

In [ ]:
a = 2
b = 5

In [ ]:
def func_name(): #func header
    print("Hi from function") #func bodyblock

func_name() #func call

Hi from function


In [145]:
def ifSumEven (a,b):
    add = a + b
    if add%2 == 0:
        return True
    else:
        return False 

if ifSumEven(2,5): 
    print("Even")
else: 
    print("Odd")

Odd


Return means get out of the function and go back to where you were called

In [147]:
def func_name(): #func header
    return
    print("Hi from function") #func bodyblock

func_name() #func call

Anything after the return statement does not work

In [ ]:
#Update from function earlier that has values of a and b set 
# if someone forgets to input them in the function

def ifSumEven (a=0,b=0):
    add = a + b
    if add%2 == 0:
        return True
    else:
        return False 

if ifSumEven(2,5): 
    print("Even")
else: 
    print("Odd")

Odd


Numpy

Its an external package that needs to be imported every time

In [153]:
import numpy as np

my_list = [1,2,3,4,5]
my_list1 = [1,2,"hi",True,4.1]

arr = np.array(my_list)
arr1 = np.array(my_list1)

#arrays have the same data type throughout 
print(type(my_list)) #list
print(type(arr)) #nparray

<class 'list'>
<class 'numpy.ndarray'>


Numpy Array has dimmensions (1d, 2d, etc) but you cant start variable as a number
so OneD

In [156]:
OneD = np.array([1,2,3,4])
TwoD = np.array([[1,2,3],[4,5,6]])
#error print (np.array([[1,2,3],[4,5]]))
#3 sides versus 2 side
ThreeD = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#A list of lists of lists! All have to be the same size. 

In [ ]:
OneD[2]
#Index 2 in array OneD

np.int64(3)

Ignore the 64 bits part you only need 3

In [ ]:
TwoD[1]
#returns the first list

array([4, 5, 6])

In [ ]:
my_list=[[1,2],[3,4]]
my_list [0] [0]
#find the index 0 list and the index 0 number in that list
#this does not work the same for arrays

1

In [163]:
#same as above but slightly different syntax
TwoD[1,2]

np.int64(6)

In [ ]:
#slicing arrays 
OneD[1:3]

array([2, 3])

Shaping Arrays

In [ ]:
#ndmin makes it 2 dimmensiional
arr=np.array([1,2,3],ndmin=2)
print(arr)

[[1 2 3]]


In [ ]:
#reshape function (rows,columns)
arr = np.array([1,2,3,4,5,6,7,8,])
newarr = arr.reshape(4,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#sorts it (it was already sorted)
newarr=np.sort(arr)
print(newarr)

[1 2 3 4 5 6 7 8]


In [ ]:
#sorts the first list, then sorts the second list
arr = [[3,2,4],[5,0,1]]
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

Dictionaries 

dict = {Key : value(s),
        Key: value(s)}

Keys are always unique but values can repeat. Every key needs to be unique because we access data in dictionary using keys. One Key can have multiple values

In [170]:
my_dict = {"brand":"BMW",
            "model":"X5",
            "year": 2010}

print(my_dict)

{'brand': 'BMW', 'model': 'X5', 'year': 2010}


In [ ]:
#find the value of the brand
print(my_dict["model"])
#key is something bigger and value is something within that bigger

X5


In [ ]:
#it chooses the last one if there are duplicates 
my_dict = {"brand":"BMW",
            "model":"X5",
            "year": 2010,
            "year": 2025}

print(my_dict)

{'brand': 'BMW', 'model': 'X5', 'year': 2025}


In [174]:
#values can be a list
my_dict = {"brand":"BMW",
            "model":["X5","X7","X9"],
            "year": 2010,
            "year": 2025}
print(my_dict)

{'brand': 'BMW', 'model': ['X5', 'X7', 'X9'], 'year': 2025}


In [ ]:
print(my_dict["model"][0])

X5


Pandas 

In [177]:
my_dict = {"brand":["BMW","Audi","Lamborgini"],
            "model":["X5","X7","X9"]}

In [179]:
import pandas as pd


df = pd.DataFrame(my_dict)
print(df)

        brand model
0         BMW    X5
1        Audi    X7
2  Lamborgini    X9


In [181]:
print(df.loc[0])

brand    BMW
model     X5
Name: 0, dtype: object


In [ ]:
#from this dataframe return the 0th row and the 1st row
print(df.loc[[0,1]])

  brand model
0   BMW    X5
1  Audi    X7


In [184]:
df = pd.DataFrame(my_dict, index = ["car1", "car2", "car3"])
print(df)

           brand model
car1         BMW    X5
car2        Audi    X7
car3  Lamborgini    X9


In [186]:
#how would you locate the index 0 car 
print(df.loc["car1"])

brand    BMW
model     X5
Name: car1, dtype: object


In [ ]:
#read CVS
#pd.read_csv("<filename>")
#takes the CVS file and makes it a dataframe

In [ ]:
#non-null tells you the number of not empty values
#Dtype is also important object = string
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, car1 to car3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   brand   3 non-null      object
 1   model   3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
None


Cleaning
newdf = df.dropnow()
All rows of empty cells will be dropped. Removes the row which will cause data loss. You might want to use dummy variables instead 